### ISSUE TITLE
Import Petri Net operator undesired behavior w.r.t. accepting petri nets

### ISSUE THREAD

**Issue by abolt** [rapidprom/rapidprom-source#18]
If the .pnml file contains an accepting petri net, it does not import anything at all

It should either try to import it anyway or not allow to use it as input (for example, by using another extension)

**Comment by s-j-v-zelst** [comment]
Please provide an example because it works with the attached file.

<?xml version="1.0" encoding="ISO-8859-1"?>
<pnml><net id="net1" type="http://www.pnml.org/version-2009/grammar/pnmlcoremodel"><name><text>Unlabeled net</text></name><page id="n0"><name><text/></name><place id="n1"><name><text>p1</text></name><toolspecific tool="ProM" version="6.4" localNodeID="11955506-d627-46dc-8079-465ed157177d"/><graphics><position x="25.0" y="25.0"/><dimension x="40.0" y="40.0"/></graphics><initialMarking><text>1</text></initialMarking></place><place id="n2"><name><text>p2</text></name><toolspecific tool="ProM" version="6.4" localNodeID="f34aaf6b-46cf-4d48-985b-a3a2e34203a0"/><graphics><position x="25.0" y="25.0"/><dimension x="40.0" y="40.0"/></graphics></place><transition id="n3"><name><text>a</text></name><toolspecific tool="ProM" version="6.4" activity="a" localNodeID="c057de23-2c92-45c2-907f-96efefbdd780"/><graphics><position x="25.0" y="25.0"/><dimension x="40.0" y="40.0"/><fill color="#FFFFFF"/></graphics></transition><arc id="arc4" source="n1" target="n3"><name><text>1</text></name><toolspecific tool="ProM" version="6.4" localNodeID="e9b0e5ca-91f8-47b3-b8c5-2db8c9e39784"/><arctype><text>normal</text></arctype></arc><arc id="arc5" source="n3" target="n2"><name><text>1</text></name><toolspecific tool="ProM" version="6.4" localNodeID="f9aea4fc-a1a6-4e11-a2ed-fd0a4e071426"/><arctype><text>normal</text></arctype></arc></page><finalmarkings><marking><place idref="n1"><text>0</text></place><place idref="n2"><text>1</text></place></marking></finalmarkings></net></pnml>

**Comment by abolt** [comment]
Here is an example: it can be imported with both the Accepting Petri Net and Normal Petri Net operators. However, only the Acccepting Petri net shows something.

**Comment by s-j-v-zelst** [comment]
This has been fixed by Eric.
He now uses an .apnml extension for accepting petri nets.
I think updating Accepting Petri nets to the latest version will solve this

**Comment by abolt** [comment]
I know, I asked him to do it ;)

**Comment by abolt** [comment]
updated to the last acceptingpetrinet package
